modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "omegaconfig"
version = "${version}"
displayName = "Omega Config Architectury"
authors = "Frqnny"
description = '''
Lightweight config library
'''
#logoFile = ""

[[dependencies.omega-config]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.omega-config]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.omega-config]]
modId = "architectury"
type = "required"
versionRange = "[12.1.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "omega-config.mixins.json"
