modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/frqnny/omega-config-architectury"
license = "MIT"

[[mods]]
modId = "omegaconfig"
version = "${version}"
displayName = "A lightweight configuration library by Draylar and Frqnny"
authors = "Frqnny"
description = '''
Lightweight config library
'''

[[dependencies.omega-config]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.omega-config]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.omega-config]]
modId = "architectury"
type = "required"
versionRange = "[16.0.3,)"
ordering = "AFTER"
side = "BOTH"
